controller:
  ingressClassResource:
    name: internal-nginx-02  # default: nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/internal-ingress-nginx-02"  # default: k8s.io/ingress-nginx